version: "3"
services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: broder
      PORTGRES_DB: broder
      POSTGRES_PASSWORD: password

  backend:
    image: mollee/broder-backend:dev
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    environment:
      DB_USER: broder
      DB_NAME: broder
      DB_PASS: password
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./backend/src:/usr/src/app/src

  frontend:
    image: mollee/broder-frontend:dev
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    depends_on:
      - backend
    stdin_open: "true"
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
